# Test


In [1]:
import numpy as np

np3 = np.array([
	[
		[1,2,3],
		[4,5,6]
	],
	[
		[7,8,9],
		[10,11,12]
	]
])

print(np3.shape)

for x in np.nditer(np3):
	print(x)

(2, 2, 3)
1
2
3
4
5
6
7
8
9
10
11
12


In [2]:
array = np.random.randint(0, 10, (2, 3, 4, 5))

print(array)

for x in np.nditer(array):
  print(x)

[[[[3 4 3 0 0]
   [8 3 5 7 8]
   [9 3 7 1 1]
   [0 1 8 8 5]]

  [[0 7 3 7 1]
   [0 3 5 3 0]
   [1 1 8 5 8]
   [8 3 9 0 3]]

  [[2 9 0 3 2]
   [9 1 1 7 9]
   [4 5 3 6 2]
   [8 6 4 3 8]]]


 [[[2 8 8 6 5]
   [7 4 6 8 6]
   [5 8 0 7 1]
   [0 3 6 3 2]]

  [[0 4 4 1 0]
   [0 8 5 5 4]
   [9 7 3 6 9]
   [5 6 0 3 1]]

  [[3 3 8 8 4]
   [5 7 0 4 1]
   [4 0 8 5 7]
   [2 8 9 5 7]]]]
3
4
3
0
0
8
3
5
7
8
9
3
7
1
1
0
1
8
8
5
0
7
3
7
1
0
3
5
3
0
1
1
8
5
8
8
3
9
0
3
2
9
0
3
2
9
1
1
7
9
4
5
3
6
2
8
6
4
3
8
2
8
8
6
5
7
4
6
8
6
5
8
0
7
1
0
3
6
3
2
0
4
4
1
0
0
8
5
5
4
9
7
3
6
9
5
6
0
3
1
3
3
8
8
4
5
7
0
4
1
4
0
8
5
7
2
8
9
5
7


In [6]:
import numpy as np

np1 = np.array([3, 6, 0, 1, 2, 3, 4, 5])

x = np.where(np1 == 3) # 4

print(x) # (array([0, 5]),)

print(x[0]) # [0 5]

print(np1[x[0]]) # [3 3]

y = np.where(np1 % 2 == 0) # 4

print(y) # (array([1, 2, 4, 6]),)


(array([0, 5]),)
[0 5]
[3 3]
(array([1, 2, 4, 6]),)


In [8]:
import numpy as np

np1 = np.array([3, 6, 0, 1, 2, 3, 4, 5])

filtered = []

for thing in np1:
	if thing % 2 == 0:
		filtered.append(True)
	else:
		filtered.append(False)

print(np1[filtered])

filtered2 = np1 % 2 == 0
print(np1[filtered2])


[6 0 2 4]
[6 0 2 4]
